

-- ------------------------------------------------------------------------------
-- This is auto-generated SQL script.
-- ------------------------------------------------------------------------------
-- This DDL was generated by 'Devart SSDLToSQLite.tt' template.
-- SQL is generated on: 12/02/2013 19:26:13
-- Generated from EDMX file: D:\svnroot\MediaPortal-1-Git_Commit-Titan\TvEngine3\Mediaportal\TV\Server\TVDatabase\EntityModel\Model.edmx
-- ------------------------------------------------------------------------------

-- ------------------------------------------------------------------------------
-- Dropping existing tables
-- ------------------------------------------------------------------------------
DROP TABLE "CanceledSchedules";
DROP TABLE "Cards";
DROP TABLE "CardGroups";
DROP TABLE "CardGroupMaps";
DROP TABLE "Channels";
DROP TABLE "ChannelGroups";
DROP TABLE "ChannelLinkageMaps";
DROP TABLE "ChannelMaps";
DROP TABLE "Conflicts";
DROP TABLE "DisEqcMotors";
DROP TABLE "Favorites";
DROP TABLE "GroupMaps";
DROP TABLE "Histories";
DROP TABLE "Keywords";
DROP TABLE "KeywordMaps";
DROP TABLE "PendingDeletions";
DROP TABLE "PersonalTVGuideMaps";
DROP TABLE "Programs";
DROP TABLE "ProgramCategories";
DROP TABLE "ProgramCredits";
DROP TABLE "Recordings";
DROP TABLE "RuleBasedSchedules";
DROP TABLE "Satellites";
DROP TABLE "Schedules";
DROP TABLE "ScheduleRulesTemplates";
DROP TABLE "Settings";
DROP TABLE "SoftwareEncoders";
DROP TABLE "Timespans";
DROP TABLE "TuningDetails";
DROP TABLE "TvMovieMappings";
DROP TABLE "Versions";
DROP TABLE "LnbTypes";
DROP TABLE "RecordingCredits";
DROP TABLE "TvGuideCategories";

-- ------------------------------------------------------------------------------
-- Creating all tables
-- ------------------------------------------------------------------------------

-- Table "CanceledSchedules"
CREATE TABLE "CanceledSchedules"  ( 
    "IdCanceledSchedule" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdSchedule" integer NOT NULL,
    "IdChannel" integer NOT NULL,
    "CancelDateTime" datetime NOT NULL,
    CONSTRAINT "FK_ScheduleCanceledSchedule" FOREIGN KEY ("IdSchedule")
    REFERENCES "Schedules" ("IdSchedule")
);

-- Table "Cards"
CREATE TABLE "Cards"  ( 
    "IdCard" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "DevicePath" varchar(2000) NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Priority" integer NOT NULL,
    "GrabEPG" boolean NOT NULL,
    "LastEpgGrab" datetime NULL,
    "RecordingFolder" varchar(256) NOT NULL,
    "Enabled" boolean NOT NULL,
    "CamType" integer NOT NULL,
    "TimeshiftingFolder" varchar(256) NOT NULL,
    "DecryptLimit" integer NOT NULL,
    "PreloadCard" boolean NOT NULL,
    "NetProvider" integer NOT NULL,
    "IdleMode" integer NOT NULL,
    "MultiChannelDecryptMode" integer NOT NULL,
    "AlwaysSendDiseqcCommands" boolean NOT NULL,
    "DiseqcCommandRepeatCount" integer NOT NULL,
    "PidFilterMode" integer NOT NULL,
    "UseCustomTuning" boolean NOT NULL,
    "UseConditionalAccess" boolean NOT NULL
);

-- Table "CardGroups"
CREATE TABLE "CardGroups"  ( 
    "IdCardGroup" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Name" varchar(255) NOT NULL
);

-- Table "CardGroupMaps"
CREATE TABLE "CardGroupMaps"  ( 
    "IdMapping" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdCard" integer NOT NULL,
    "IdCardGroup" integer NOT NULL,
    CONSTRAINT "FK_CardGroupMapCard" FOREIGN KEY ("IdCard")
    REFERENCES "Cards" ("IdCard"),
    CONSTRAINT "FK_CardGroupMapCardGroup" FOREIGN KEY ("IdCardGroup")
    REFERENCES "CardGroups" ("IdCardGroup")
);

-- Table "Channels"
CREATE TABLE "Channels"  ( 
    "IdChannel" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "TimesWatched" integer NOT NULL,
    "TotalTimeWatched" datetime NULL,
    "GrabEpg" boolean NOT NULL,
    "LastGrabTime" datetime NULL,
    "SortOrder" integer NOT NULL,
    "VisibleInGuide" boolean NOT NULL,
    "ExternalId" varchar(200) NULL,
    "DisplayName" varchar(200) NOT NULL,
    "EpgHasGaps" boolean NOT NULL,
    "MediaType" integer NOT NULL,
    "ChannelNumber" integer NOT NULL
);

-- Table "ChannelGroups"
CREATE TABLE "ChannelGroups"  ( 
    "IdGroup" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "GroupName" varchar(200) NOT NULL,
    "SortOrder" integer NOT NULL,
    "MediaType" integer NOT NULL
);

-- Table "ChannelLinkageMaps"
CREATE TABLE "ChannelLinkageMaps"  ( 
    "IdMapping" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdPortalChannel" integer NOT NULL,
    "IdLinkedChannel" integer NOT NULL,
    "DisplayName" varchar(200) NOT NULL,
    CONSTRAINT "FK_ChannelLinkMap" FOREIGN KEY ("IdLinkedChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ChannelPortalMap" FOREIGN KEY ("IdPortalChannel")
    REFERENCES "Channels" ("IdChannel")
);

-- Table "ChannelMaps"
CREATE TABLE "ChannelMaps"  ( 
    "IdChannelMap" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "IdCard" integer NOT NULL,
    "EpgOnly" boolean NOT NULL,
    CONSTRAINT "FK_CardChannelMap" FOREIGN KEY ("IdCard")
    REFERENCES "Cards" ("IdCard"),
    CONSTRAINT "FK_ChannelChannelMap" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel")
);

-- Table "Conflicts"
CREATE TABLE "Conflicts"  ( 
    "IdConflict" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdSchedule" integer NOT NULL,
    "IdConflictingSchedule" integer NOT NULL,
    "IdChannel" integer NOT NULL,
    "ConflictDate" datetime NOT NULL,
    "IdCard" integer NULL,
    CONSTRAINT "FK_CardConflict" FOREIGN KEY ("IdCard")
    REFERENCES "Cards" ("IdCard"),
    CONSTRAINT "FK_ChannelConflict" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ScheduleConflict" FOREIGN KEY ("IdSchedule")
    REFERENCES "Schedules" ("IdSchedule"),
    CONSTRAINT "FK_ScheduleConflict1" FOREIGN KEY ("IdConflictingSchedule")
    REFERENCES "Schedules" ("IdSchedule")
);

-- Table "DisEqcMotors"
CREATE TABLE "DisEqcMotors"  ( 
    "IdDiSEqCMotor" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdCard" integer NOT NULL,
    "IdSatellite" integer NOT NULL,
    "Position" integer NOT NULL,
    CONSTRAINT "FK_DisEqcMotorCard" FOREIGN KEY ("IdCard")
    REFERENCES "Cards" ("IdCard"),
    CONSTRAINT "FK_DisEqcMotorSatellite" FOREIGN KEY ("IdSatellite")
    REFERENCES "Satellites" ("IdSatellite")
);

-- Table "Favorites"
CREATE TABLE "Favorites"  ( 
    "IdFavorite" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdProgram" integer NOT NULL,
    "Priority" integer NOT NULL,
    "TimesWatched" integer NOT NULL
);

-- Table "GroupMaps"
CREATE TABLE "GroupMaps"  ( 
    "IdMap" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdGroup" integer NOT NULL,
    "IdChannel" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "FK_GroupMapChannelGroup" FOREIGN KEY ("IdGroup")
    REFERENCES "ChannelGroups" ("IdGroup"),
    CONSTRAINT "FK_GroupMapChannel" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel")
);

-- Table "Histories"
CREATE TABLE "Histories"  ( 
    "IdHistory" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "StartTime" datetime NOT NULL,
    "EndTime" datetime NOT NULL,
    "Title" varchar(1000) NOT NULL,
    "Description" varchar(1000) NOT NULL,
    "Recorded" boolean NOT NULL,
    "Watched" integer NOT NULL,
    "IdProgramCategory" integer NULL,
    CONSTRAINT "FK_ChannelHistory" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ProgramCategoryHistory" FOREIGN KEY ("IdProgramCategory")
    REFERENCES "ProgramCategories" ("IdProgramCategory")
);

-- Table "Keywords"
CREATE TABLE "Keywords"  ( 
    "IdKeyword" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "KeywordName" varchar(200) NOT NULL,
    "Rating" integer NOT NULL,
    "AutoRecord" boolean NOT NULL,
    "SearchIn" integer NOT NULL
);

-- Table "KeywordMaps"
CREATE TABLE "KeywordMaps"  ( 
    "IdKeywordMap" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdKeyword" integer NOT NULL,
    "IdChannelGroup" integer NOT NULL,
    CONSTRAINT "FK_KeywordKeywordMap" FOREIGN KEY ("IdKeyword")
    REFERENCES "Keywords" ("IdKeyword"),
    CONSTRAINT "FK_KeywordMapChannelGroup" FOREIGN KEY ("IdChannelGroup")
    REFERENCES "ChannelGroups" ("IdGroup")
);

-- Table "PendingDeletions"
CREATE TABLE "PendingDeletions"  ( 
    "IdPendingDeletion" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "FileName" text NOT NULL
);

-- Table "PersonalTVGuideMaps"
CREATE TABLE "PersonalTVGuideMaps"  ( 
    "IdPersonalTVGuideMap" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdKeyword" integer NOT NULL,
    "IdProgram" integer NOT NULL,
    CONSTRAINT "FK_ProgramPersonalTVGuideMap" FOREIGN KEY ("IdProgram")
    REFERENCES "Programs" ("IdProgram"),
    CONSTRAINT "FK_KeywordPersonalTVGuideMap" FOREIGN KEY ("IdKeyword")
    REFERENCES "Keywords" ("IdKeyword")
);

-- Table "Programs"
CREATE TABLE "Programs"  ( 
    "IdProgram" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "StartTime" datetime NOT NULL,
    "EndTime" datetime NOT NULL,
    "Title" varchar(2000) NOT NULL,
    "Description" varchar(8000) NOT NULL,
    "SeriesNum" varchar(200) NOT NULL,
    "EpisodeNum" varchar(200) NOT NULL,
    "OriginalAirDate" datetime NULL,
    "Classification" varchar(200) NOT NULL,
    "StarRating" integer NOT NULL,
    "ParentalRating" integer NOT NULL,
    "EpisodeName" text NOT NULL,
    "EpisodePart" text NOT NULL,
    "State" integer NOT NULL,
    "PreviouslyShown" boolean NOT NULL,
    "IdProgramCategory" integer NULL,
    "StartTimeDayOfWeek" smallint NOT NULL,
    "EndTimeDayOfWeek" smallint NOT NULL,
    "EndTimeOffset" datetime NOT NULL,
    "StartTimeOffset" datetime NOT NULL,
    CONSTRAINT "FK_ChannelProgram" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ProgramProgramCategory" FOREIGN KEY ("IdProgramCategory")
    REFERENCES "ProgramCategories" ("IdProgramCategory")
);

-- Table "ProgramCategories"
CREATE TABLE "ProgramCategories"  ( 
    "IdProgramCategory" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Category" varchar(50) NOT NULL,
    "IdTvGuideCategory" integer NULL,
    CONSTRAINT "FK_TvGuideCategoryProgramCategory" FOREIGN KEY ("IdTvGuideCategory")
    REFERENCES "TvGuideCategories" ("IdTvGuideCategory")
);

-- Table "ProgramCredits"
CREATE TABLE "ProgramCredits"  ( 
    "IdProgramCredit" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdProgram" integer NOT NULL,
    "Person" varchar(200) NOT NULL,
    "Role" varchar(50) NOT NULL,
    CONSTRAINT "FK_ProgramProgramCredit" FOREIGN KEY ("IdProgram")
    REFERENCES "Programs" ("IdProgram")
);

-- Table "Recordings"
CREATE TABLE "Recordings"  ( 
    "IdRecording" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NULL,
    "StartTime" datetime NOT NULL,
    "EndTime" datetime NOT NULL,
    "Title" varchar(2000) NOT NULL,
    "Description" varchar(8000) NOT NULL,
    "FileName" varchar(260) NOT NULL,
    "KeepUntil" integer NOT NULL,
    "KeepUntilDate" datetime NULL,
    "TimesWatched" integer NOT NULL,
    "StopTime" integer NOT NULL,
    "EpisodeName" text NOT NULL,
    "SeriesNum" varchar(200) NOT NULL,
    "EpisodeNum" varchar(200) NOT NULL,
    "EpisodePart" text NOT NULL,
    "IsRecording" boolean NOT NULL,
    "IdSchedule" integer NULL,
    "MediaType" integer NOT NULL,
    "IdProgramCategory" integer NULL,
    CONSTRAINT "FK_ChannelRecording" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ScheduleRecording" FOREIGN KEY ("IdSchedule")
    REFERENCES "Schedules" ("IdSchedule"),
    CONSTRAINT "FK_RecordingProgramCategory" FOREIGN KEY ("IdProgramCategory")
    REFERENCES "ProgramCategories" ("IdProgramCategory")
);

-- Table "RuleBasedSchedules"
CREATE TABLE "RuleBasedSchedules"  ( 
    "IdRuleBasedSchedule" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "ScheduleName" varchar(256) NOT NULL,
    "MaxAirings" integer NOT NULL,
    "Priority" integer NOT NULL,
    "Directory" varchar(1024) NOT NULL,
    "Quality" integer NOT NULL,
    "KeepMethod" integer NOT NULL,
    "KeepDate" datetime NULL,
    "PreRecordInterval" integer NOT NULL,
    "PostRecordInterval" integer NOT NULL,
    "Rules" text NULL
);

-- Table "Satellites"
CREATE TABLE "Satellites"  ( 
    "IdSatellite" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "SatelliteName" varchar(200) NOT NULL,
    "TransponderFileName" varchar(200) NOT NULL
);

-- Table "Schedules"
CREATE TABLE "Schedules"  ( 
    "IdSchedule" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "ScheduleType" integer NOT NULL,
    "ProgramName" varchar(256) NOT NULL,
    "StartTime" datetime NOT NULL,
    "EndTime" datetime NOT NULL,
    "MaxAirings" integer NOT NULL,
    "Priority" integer NOT NULL,
    "Directory" varchar(1024) NOT NULL,
    "Quality" integer NOT NULL,
    "KeepMethod" integer NOT NULL,
    "KeepDate" datetime NULL,
    "PreRecordInterval" integer NOT NULL,
    "PostRecordInterval" integer NOT NULL,
    "Canceled" datetime NOT NULL,
    "Series" boolean NOT NULL,
    "IdParentSchedule" integer NULL,
    CONSTRAINT "FK_ChannelSchedule" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_ScheduleParentSchedule" FOREIGN KEY ("IdParentSchedule")
    REFERENCES "Schedules" ("IdSchedule")
);

-- Table "ScheduleRulesTemplates"
CREATE TABLE "ScheduleRulesTemplates"  ( 
    "IdScheduleRulesTemplate" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Name" varchar(50) NOT NULL,
    "Rules" text NOT NULL,
    "Enabled" boolean NOT NULL,
    "Usages" integer NOT NULL,
    "Editable" boolean NOT NULL
);

-- Table "Settings"
CREATE TABLE "Settings"  ( 
    "IdSetting" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Tag" varchar(200) NOT NULL,
    "Value" varchar(4096) NOT NULL
);

-- Table "SoftwareEncoders"
CREATE TABLE "SoftwareEncoders"  ( 
    "IdEncoder" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Priority" integer NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Type" integer NOT NULL,
    "Reusable" boolean NOT NULL
);

-- Table "Timespans"
CREATE TABLE "Timespans"  ( 
    "IdTimespan" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "StartTime" datetime NOT NULL,
    "EndTime" datetime NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "IdKeyword" integer NOT NULL
);

-- Table "TuningDetails"
CREATE TABLE "TuningDetails"  ( 
    "IdTuning" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Provider" varchar(200) NOT NULL,
    "ChannelType" integer NOT NULL,
    "ChannelNumber" integer NOT NULL,
    "Frequency" integer NOT NULL,
    "CountryId" integer NOT NULL,
    "NetworkId" integer NOT NULL,
    "TransportId" integer NOT NULL,
    "ServiceId" integer NOT NULL,
    "PmtPid" integer NOT NULL,
    "FreeToAir" boolean NOT NULL,
    "Modulation" integer NOT NULL,
    "Polarisation" integer NOT NULL,
    "Symbolrate" integer NOT NULL,
    "DiSEqC" integer NOT NULL,
    "Bandwidth" integer NOT NULL,
    "MajorChannel" integer NOT NULL,
    "MinorChannel" integer NOT NULL,
    "VideoSource" integer NOT NULL,
    "TuningSource" integer NOT NULL,
    "Band" integer NOT NULL,
    "SatIndex" integer NOT NULL,
    "InnerFecRate" integer NOT NULL,
    "Pilot" integer NOT NULL,
    "RollOff" integer NOT NULL,
    "Url" varchar(200) NOT NULL,
    "Bitrate" integer NOT NULL,
    "AudioSource" integer NOT NULL,
    "IsVCRSignal" boolean NOT NULL,
    "MediaType" integer NOT NULL,
    "IdLnbType" integer NULL,
    CONSTRAINT "FK_ChannelTuningDetail" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel"),
    CONSTRAINT "FK_LnbTypeTuningDetail" FOREIGN KEY ("IdLnbType")
    REFERENCES "LnbTypes" ("IdLnbType")
);

-- Table "TvMovieMappings"
CREATE TABLE "TvMovieMappings"  ( 
    "IdMapping" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdChannel" integer NOT NULL,
    "StationName" varchar(200) NOT NULL,
    "TimeSharingStart" varchar(200) NOT NULL,
    "TimeSharingEnd" varchar(200) NOT NULL,
    CONSTRAINT "FK_ChannelTvMovieMapping" FOREIGN KEY ("IdChannel")
    REFERENCES "Channels" ("IdChannel")
);

-- Table "Versions"
CREATE TABLE "Versions"  ( 
    "IdVersion" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "VersionNumber" integer NOT NULL
);

-- Table "LnbTypes"
CREATE TABLE "LnbTypes"  ( 
    "IdLnbType" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Name" text NOT NULL,
    "LowBandFrequency" integer NOT NULL,
    "HighBandFrequency" integer NOT NULL,
    "SwitchFrequency" integer NOT NULL,
    "IsBandStacked" boolean NOT NULL,
    "IsToroidal" boolean NOT NULL
);

-- Table "RecordingCredits"
CREATE TABLE "RecordingCredits"  ( 
    "IdRecordingCredit" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IdRecording" integer NOT NULL,
    "Person" varchar(200) NOT NULL,
    "Role" varchar(50) NOT NULL,
    CONSTRAINT "FK_RecordingRecordingCredit" FOREIGN KEY ("IdRecording")
    REFERENCES "Recordings" ("IdRecording")
);

-- Table "TvGuideCategories"
CREATE TABLE "TvGuideCategories"  ( 
    "IdTvGuideCategory" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Name" text NOT NULL,
    "IsMovie" boolean NOT NULL,
    "IsEnabled" boolean NOT NULL
);
